"""Add comprehensive patient fields per clinical feedback

Revision ID: 60ef3a03d9bf
Revises: d5167e91d1c5
Create Date: 2026-06-13 01:09:44.352028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ef3a03d9bf'
down_revision: Union[str, Sequence[str], None] = 'd5167e91d1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_surgeries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('surgery_date', sa.Date(), nullable=False),
    sa.Column('procedure_name', sa.String(length=255), nullable=False),
    sa.Column('facility', sa.String(length=255), nullable=False),
    sa.Column('anaesthetic_used', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_of_kin_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_relationship', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=20), server_default='en', nullable=False))
        batch_op.add_column(sa.Column('has_insurance', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('insurance_provider', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('insurance_member_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('insurance_plan_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('known_allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chronic_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_medications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('family_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('social_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('immunization_record', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emergency_critical_allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_primary', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_secondary', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('emergency_contact_secondary')
        batch_op.drop_column('emergency_contact_primary')
        batch_op.drop_column('emergency_critical_allergies')
        batch_op.drop_column('immunization_record')
        batch_op.drop_column('social_history')
        batch_op.drop_column('family_history')
        batch_op.drop_column('current_medications')
        batch_op.drop_column('chronic_conditions')
        batch_op.drop_column('known_allergies')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('insurance_plan_type')
        batch_op.drop_column('insurance_member_number')
        batch_op.drop_column('insurance_provider')
        batch_op.drop_column('has_insurance')
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('occupation')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('next_of_kin_phone')
        batch_op.drop_column('next_of_kin_relationship')
        batch_op.drop_column('next_of_kin_name')

    op.drop_table('past_surgeries')
    # ### end Alembic commands ###
