"""Add countries table and country_id on users and patients

Revision ID: 8ba23e317f24
Revises: b200a1d08850
Create Date: 2026-06-13 13:22:33.169127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba23e317f24'
down_revision: Union[str, Sequence[str], None] = 'b200a1d08850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('phone_country_code', sa.String(length=10), nullable=False),
    sa.Column('default_language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('national_id_label', sa.String(length=50), nullable=False),
    sa.Column('national_id_format_regex', sa.String(length=255), nullable=False),
    sa.Column('national_id_hint', sa.String(length=255), nullable=True),
    sa.Column('phone_format_regex', sa.String(length=255), nullable=False),
    sa.Column('phone_hint', sa.String(length=255), nullable=True),
    sa.Column('medical_council_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_code'), ['code'], unique=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_patients_country_id', 'countries', ['country_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_users_country_id', 'countries', ['country_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_country_id', type_='foreignkey')
        batch_op.drop_column('country_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patients_country_id', type_='foreignkey')
        batch_op.drop_column('country_id')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_code'))

    op.drop_table('countries')
    # ### end Alembic commands ###
