"""Add drug_interaction_rules table

Revision ID: b200a1d08850
Revises: a597788bf23e
Create Date: 2026-06-13 13:01:29.378225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b200a1d08850'
down_revision: Union[str, Sequence[str], None] = 'a597788bf23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_interaction_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('interacts_with_drug', sa.String(length=255), nullable=True),
    sa.Column('interacts_with_condition', sa.String(length=255), nullable=True),
    sa.Column('interacts_with_allergy', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('warning_message', sa.Text(), nullable=False),
    sa.Column('clinical_action', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drug_interaction_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drug_interaction_rules_drug_name'), ['drug_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug_interaction_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drug_interaction_rules_drug_name'))

    op.drop_table('drug_interaction_rules')
    # ### end Alembic commands ###
